services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - 127.0.0.1:3000:3000
        volumes:
            - ./api:/app
            - ./package.json:/app/package.json
            - node_modules:/app/node_modules
        command: npm start
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
            - .:/app
        ports:
            - 127.0.0.1:${MYSQL_PORT}:3306
    web:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - 80:3000
        volumes:
            - ./web:/app
            - ./package.json:/app/package.json
            - node_modules:/app/node_modules
        command: npm start
        # command: tail -f /dev/null #idle container
volumes:
    node_modules:
    mysql:
